stages:
  - lint
  - typecheck
  - audit
  - test
  - deploy


# template for uv installation
.ci-template:
  # image: python:3.13-slim
  cache:
    key: "uv-cache"
    paths:
      - .uv-cache
  variables:
    UV_CACHE_DIR: .uv-cache
  before_script:
  - apt-get update && apt-get install -y git
  - python -m pip install --upgrade pip
  - python -m pip install uv
  - uv sync --frozen --group dev


# pre-commit hooks
lint:
  stage: lint
  extends: .ci-template
  script:
    - uv run pre-commit run --all-files --show-diff-on-failure
  allow_failure: true


# mypy static type checker
typecheck:
  stage: typecheck
  extends: .ci-template
  script:
    - uv run mypy fpi
  allow_failure: true


# look for vulnerable dependencies
audit:
  stage: audit
  extends: .ci-template
  script:
    - '# Ignore known advisory GHSA-2qfp-q593-8484 (brotli<=1.1.0) until a fixed wheel is available in our env'
    - uv run pip-audit . --ignore-vuln GHSA-2qfp-q593-8484
  allow_failure: true
  only:
    - main
    - test-main


# unit tests, integration tests, doctests, and behave tests
test:
  stage: test
  extends: .ci-template
  script:
    - uv run pytest --doctest-modules --maxfail=3 --disable-warnings -q
    - uv run behave tests/behave/features


# deploy on Raspberry Pi and restart FPI with new code
deploy_raspberry:
  stage: deploy
  only:
    - main
  tags:
    - raspberry
  script:
    - echo "Déploiement sur la Raspberry..."
    - cd /home/nicolascollin/apps/fpi
    - git pull origin main
    - uv sync || true
    - sudo systemctl restart fpi.service
    - echo "Lien public actuel de FPI :"
    - cat /home/nicolascollin/fpi_url.txt || echo "Aucun lien trouvé (fpi_url.txt manquant)"
    - echo "Déploiement terminé avec succès ✔️ – nouvelle version désormais en ligne."
