repos:
  # Ruff: checks + fixes
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff           # code linter
        args: ["--fix"]
      - id: ruff-format    # code formatter

  # General hooks: quick cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml            # checks pyproject.toml
      - id: end-of-file-fixer     # adds empty line at end of file
      - id: trailing-whitespace   # removes unnecessary spaces
        exclude: '\.md$'  # don't remove the double spaces (newline) in README.md
