[project]
name = "gpd-fpi"
version = "0.1.0"
description = "France Property Insight: Uni project app for Master 2 SEP"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "gradio==5.49.1",
    "pandas==2.3.3",
]

# depedencies not needed for users
[dependency-groups]
dev = [
    "mypy==1.18.2",
    "pip-audit==2.9.0",
    "pre-commit==4.3.0",
    "pytest==8.4.2",
    "ruff==0.14.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# change line length tolerance
[tool.ruff]
line-length = 120

# default linting rules + isort
[tool.ruff.lint]
select = ["E", "F", "I"]

# uv run shortcuts
[project.scripts]
main = "src.main:main"
precommit = "src.utils.aliases:precommit"
lint = "src.utils.aliases:precommit"
fpibuild = "src.utils.aliases:fpibuild"
fpirun = "src.utils.aliases:fpirun"
typecheck = "src.utils.aliases:typecheck"
audit = "src.utils.aliases:audit"
test = "src.utils.aliases:test"
