---
config:
  theme: mc
  layout: dagre
  look: neo
---
flowchart BT
 subgraph Frontend["Frontend"]
        A["Web Client Interface (Gradio)"]
  end
 subgraph Backend["Backend"]
        B["FastAPI Layer"]
        D["Processing Layer<br>(Analysis / Prediction)"]
        E["Database Access Layer (SQLAlchemy)"]
  end
 subgraph DataPipeline["Data Preparation Pipeline"]
        F["Raw Data<br>(.txt files)"]
        G["Validated &amp; Cleaned<br>(NA, duplicates, errors...)"]
        H["Processed<br>(Analysis-Ready)"]
  end
 subgraph Database["Database"]
        I["Local SQLite or<br>MySQL server"]
  end
    A -- API request --> B
    B -- Validated Request<br>(Pydantic) --> D
    D -- Query Operations --> E
    E -- Interacts with --> I
    I -- Query Results --> E
    E -- Returns Data --> D
    D -- Validated Results<br>(Pydantic) --> B
    B -- Displayed Results --> A
    F --> G
    G --> H
    H --> I
